name: JBCreditShop
version: '1.0-SNAPSHOT'
main: org.example.jbcreditshop.Main
api-version: '1.19'
authors: [ Mortality/MortalDev ]
description: Plugin used to create credit shops.
depend:
  - EcoBits